apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: h2-db
spec:
  selector:
    matchLabels:
      app: h2-db
  replicas: 1
  template:
    metadata:
      labels:
        app: h2-db
    spec:
      containers:
      - name: h2-db-container
        image: oscarfonts/h2:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 1521
          name: jdbc
        - containerPort: 81
          name: http
        livenessProbe:
          tcpSocket:
            port: jdbc
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always