apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: h2-db
spec:
  selector:
    matchLabels:
      app: h2-db
  replicas: 2
  template:
    metadata:
      labels:
        app: h2-db
    spec:
      containers:
      - name: h2-db-container
        image: oscarfonts/h2:1.4.197
        volumeMounts:
          - mountPath: /opt/h2-data
            name: data
        ports:
        - containerPort: 1521
          name: jdbc
        - containerPort: 81
          name: http
        livenessProbe:
          tcpSocket:
            port: jdbc
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: h2-db-pvc
