apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: app-ingress
spec:
    rules:
        - host: qa.k8s-schulung.viadee.cloud
          http:
              paths:
                  - backend:
                        serviceName: demo-app
                        servicePort: 80
    tls:
        - secretName: tls-k8s-schulung-viadee-cloud
