version: '3'

services:
  testapp:
    image: viadee/k8s-demo-app:latest
    ports:
    - 8080:8080
    environment:
    - spring.datasource.url=jdbc:h2:tcp://h2-db:1521/test

  testapp2:
      image: viadee/k8s-demo-app:latest
      ports:
      - 8081:8080
      environment:
      - spring.datasource.url=jdbc:h2:tcp://h2-db:1521/test

  h2-db:
    image: oscarfonts/h2:1.4.197
    ports:
    - 81:81
    volumes:
      - h2-db-data:/opt/h2-data

volumes:
  h2-db-data:

